### ISSUE TITLE
Breadcrumbs enhancement ideas

### ISSUE THREAD

**Issue by kamil-mech** [nearform/node-clinic-bubbleprof#158]
Alan and I have discussed this and we had a few ideas each, feel free to suggest more
- Integrate with browser back and forward
- Integrate with urls
- Unique identifier for each breadcrumb
- Colouring to indicate the layer, i.e. main view, cluster clump, cluster, aggregate clump, aggregate
- Integrate with sidebar search
- Add path + line number info for better code relatedness (in hover)

**Comment by BridgeAR** [comment]
@kamil-mech should we keep this open? I think if it is not important and no one asks for it, we could just go ahead and close it for now.

**Comment by kamil-mech** [comment]
Renee is currently working on this so we will close it when PR arrives
