### ISSUE TITLE
Misplaced tooltips in Safari

### ISSUE THREAD

**Issue by ShaunBaker** [nearform/node-clinic-bubbleprof#214]
Small issue with the tooltips in Safari (Mac).

<img width="1680" alt="screen shot 2018-07-17 at 14 29 38" src="https://user-images.githubusercontent.com/1176557/42823337-355ff176-89d5-11e8-8777-545e6662410d.png">

<img width="1680" alt="screen shot 2018-07-17 at 14 29 34" src="https://user-images.githubusercontent.com/1176557/42823340-35a3533a-89d5-11e8-8d4c-b5007b26fe61.png">

**Comment by AlanSl** [comment]
Fixed in https://github.com/nearform/node-clinic-bubbleprof/pull/223

Released in 1.1.4
