### ISSUE TITLE
Improve hottest method in analysis

### ISSUE THREAD

**Issue by mcollina** [nearform/node-clinic-bubbleprof#242]
In https://upload.clinicjs.org/public/a3637f063864c1f66ee9c393a06129b2683e13acc0492d42cc0213096abf1a73/7528.clinic-flame.html, the hottest method is [`insertBarrierNode`](https://github.com/nearform/node-clinic-bubbleprof/blob/master/analysis/cluster/cluster-node.js#L71-L75). This is extremely hot because `this.nodes.sort()` is being called for every insertion.

I would recommend to use a different data structure for `this.nodes`, I would recommend a Red-Black Tree or a Binary Tree. I got a lot of success in the past with https://github.com/mikolalysenko/functional-red-black-tree, but it's a bit old.

**Comment by mafintosh** [comment]
Nice finding! I have some stuff for this somewhere also.

**Comment by mcollina** [comment]
Please share! That module is a classic but a bit old.
Il giorno ven 10 ago 2018 alle 21:51 Mathias Buus <notifications@github.com>
ha scritto:

**Comment by mafintosh** [comment]
It's a BTree impl that worked quite well. I'll dig it up.

**Comment by mafintosh** [comment]
Actually let me just note that I'm pretty sure aggregateId is a simple incrementing number. Simply allocating a big static array and inserting at aggregateId index might be very fast. I'll investigate.

**Comment by BridgeAR** [comment]
@mafintosh even if `aggregateId` is a incremental number it is very likely still better to use a BTree. Arrays do not scale that well and in case an entry has to be inserted in the middle, all following entries will be moved and that is costy. If it's always attached at the end of the array, it should be fast and the sorting could just be removed (it is likely the main issue in that function). However, depending on the size of the array it would still become slow. Huge arrays are not the best data structure in JS.

**Comment by mafintosh** [comment]
@BridgeAR the keyword was big static array :) ie new Array(largeNum) and arr[aggregateId] = ... with some tricks

**Comment by mafintosh** [comment]
Do we have the original dataset used here? /cc @AlanSl I see your name in the stack

**Comment by BridgeAR** [comment]
This is fixed by #247 even tough there is probably even more potential left to improve.
