### ISSUE TITLE
do not throw on process exit with non-zero code

### ISSUE THREAD

**Issue by ovhemert** [nearform/node-clinic-bubbleprof#277]
Related to confirmed bug in nearform/node-clinic#73.

When client process terminates with an exit code > 0 like process.exit(1), an error is thrown by bubbleprof. Clinic terminates, and trace event file is not moved to logging directory. Terminating the client process this way could be intentional and trace output is still useful.

BubbleProf should report the error to the console but not throw. And still move trace event file to the logging directory for visualisation by Clinic.

**Comment by mcollina** [comment]
Fixed in #278.
