### ISSUE TITLE
Problem flagging: characteristics of likely-unnecessary nextTicks and setImmediates?

### ISSUE THREAD

**Issue by AlanSl** [nearform/node-clinic-bubbleprof#289]
Are there common characteristics a heuristic could use to spot probably-unnecessary setImmediates and nextTicks?

**Comment by mcollina** [comment]
What is a bad practice is the following:

```js
function a (cb) {
  process.nextTick(cb)
}

function b (cb) {
  a((err) => {
    process.nextTick(cb, err)
  })
}

function c (cb) {
  b((err) => {
    process.nextTick(cb, err)
  })
}

c(function (err) {
  console.log('finished', err)
}
```

I would warn after 2-3 wrappings.

Note that `process.nextTick()` and `setImmediate()` could actually be fine and needed in certain cases.
