### ISSUE TITLE
preview of async operation not shown on the links

### ISSUE THREAD

**Issue by mcollina** [nearform/node-clinic-bubbleprof#306]
See https://upload.clinicjs.org/public/bed6df30a2b0ce191b941bb6b4539c0068fffdb43008e86bca3645516a390e86/19968.clinic-bubbleprof.html
.
<img width="494" alt="schermata 2019-02-04 alle 17 49 01" src="https://user-images.githubusercontent.com/52195/52248862-43940600-28a5-11e9-9fad-55dc4072eef9.png">

<img width="1280" alt="schermata 2019-02-04 alle 19 00 18" src="https://user-images.githubusercontent.com/52195/52248849-2bbc8200-28a5-11e9-97c3-369141d53540.png">

**Comment by AlanSl** [comment]
This is very strange: on latest Bubbleprof master with updated deps using `npm run visualize-all`, it comes out fixed:

https://upload.clinicjs.org/public/de9e5b88b2673cc6a9c94e6d989428ad7455f00f7b5c447d7cf02c5a7e7d0e32/19968.clinic-bubbleprof.html

But with the exact local bubblprof codebase linked through npm link, running `clinic bubbleprof --visualize-only` shows this bug:

https://upload.clinicjs.org/public/293a186d9a34997f31c424a6d358f43cce76e0c96a786cd21f13f10e434eae9f/19968.clinic-bubbleprof.html

So it's probably a result of either some difference between those commands (which should be functionally identical), or, Clinic picking up a different dependency version than Bubbleprof would on something they both use - maybe on a dependency where they have different versioning rules? I'll fix it today.
