### ISSUE TITLE
Make frames clickable and open the source code

### ISSUE THREAD

**Issue by mafintosh** [nearform/node-clinic-bubbleprof#31]
https://nearform.slack.com/files/U8NFXJKE3/F97KK00US/image.png

Clicking on `_http_server.js` fx could open the relevant code in the users browser on Github, or in an editor if we prefer. Obvs most useful for user code and module debugging.

**Comment by BridgeAR** [comment]
What is the status here?

**Comment by mcollina** [comment]
This is still an idea, it's not currently possible to do it, we can close it.
