### ISSUE TITLE
Wall time segment start time doesn’t precede segment end time

### ISSUE THREAD

**Issue by realies** [nearform/node-clinic-bubbleprof#363]
Getting `Wall time segment start time (74163287.913) doesn’t precede segment end time (74163284.704)` when trying to inspect a Bubbleprof analysis. This is an issue with the local cli and when uploading to Clinicjs servers when ran against the same app. Any suggestions on resolving this?

[16326.clinic-bubbleprof.zip](https://github.com/nearform/node-clinic-bubbleprof/files/4486148/16326.clinic-bubbleprof.zip)

**Comment by ManAnRuck** [comment]
same issue

**Comment by jasnell** [comment]
Just a heads up... We are investigating this one
