### ISSUE TITLE
Rename `sourceNode` in the context of connections to `originNode`

### ISSUE THREAD

**Issue by AlanSl** [nearform/node-clinic-bubbleprof#70]
`sourceNode` is used with two different meanings currently: the containers of callback events in an aggregateNode, and the reference to the origin of a Connection. This is a legacy hangover from the demo code where sourceNodes were referred to as sources and connections used a common D3 convention of source/target.

To avoid confusion let's put in a PR (next week maybe) that renames `source` and `sourceNode` in the context of `Connection`s as `origin` and `originNode`.

Edit: Discussed in review here https://github.com/nearform/node-clinic-bubbleprof/pull/63#pullrequestreview-110795573

**Comment by BridgeAR** [comment]
What is the status here? Should this still be addressed / was this refactored in the meanwhile?

To me it seems like it should be pretty straight forward to put a PR together for this and it should not take long to fix it?

**Comment by AlanSl** [comment]
Yes, this is one of those 'easy but low priority' tasks that has sat at the bottom of a todo list for a long time. Some performance work I'm doing this week involves re-evaluating this area of the code so I can probably fit this in with that.

**Comment by DylanC** [comment]
@AlanSl - Has this been taken care of already?
