### ISSUE TITLE
Showing averages in the UI

### ISSUE THREAD

**Issue by mafintosh** [nearform/node-clinic-bubbleprof#79]
When optimising things like latency bubbleprof is a bit hard to use atm.

The reason is that we only show aggregated numbers and lots of benchmark tools (like autocannon) are time based.

This means as latency is optimised away, throughput increases and the aggregated numbers are the same.

Here is an example of running the external-service example from https://github.com/nearform/node-clinic-bubbleprof-examples

First one is running with 50ms latency
![2018-04-16-155608_1920x1080_scrot](https://user-images.githubusercontent.com/376661/38813245-bbb9fbfc-418e-11e8-9bd1-2c2129c2332e.png)

And the next one is with 500ms latency or 10x more
![2018-04-16-155618_1920x1080_scrot](https://user-images.githubusercontent.com/376661/38813246-bbdc4f68-418e-11e8-8008-784460ee8376.png)

Notice how the output is close to being exactly the same because the first one has much higher throughput than the second one

**Comment by BridgeAR** [comment]
What is the status here? @mafintosh

**Comment by mafintosh** [comment]
sidebar made this a ton betteer
